name: CDN Auto-Update & Tests

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  security-tests:
    name: Security & Quality Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Run security tests
        run: |
          python3 scripts/build-and-publish.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Check bundle size
        run: |
          BUNDLE_SIZE=$(du -sb src | cut -f1)
          MAX_SIZE=102400  # 100KB
          if [ $BUNDLE_SIZE -gt $MAX_SIZE ]; then
            echo "❌ Bundle size exceeds 100KB: $BUNDLE_SIZE bytes"
            exit 1
          fi
          echo "✅ Bundle size OK: $BUNDLE_SIZE bytes"
  
  purge-cdn:
    name: Purge CDN Cache
    runs-on: ubuntu-latest
    needs: security-tests
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
    
    steps:
      - name: Extract version
        id: version
        run: |
          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION="main"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      
      - name: Purge jsdelivr cache
        run: |
          # Purge main index
          curl -X POST "https://purge.jsdelivr.net/gh/${{ github.repository }}@${{ steps.version.outputs.version }}/src/index.js"
          
          # Purge all core files
          for file in FrontendRAFT.js CacheLayer.js StreamManager.js BatchManager.js OptimisticEngine.js QueryEngine.js; do
            curl -X POST "https://purge.jsdelivr.net/gh/${{ github.repository }}@${{ steps.version.outputs.version }}/src/core/$file"
          done
          
          echo "✅ CDN cache purged for ${{ steps.version.outputs.version }}"
      
      - name: Wait for CDN
        run: |
          echo "Waiting 30 seconds for CDN propagation..."
          sleep 30
      
      - name: Verify CDN availability
        run: |
          URL="https://cdn.jsdelivr.net/gh/${{ github.repository }}@${{ steps.version.outputs.version }}/src/index.js"
          echo "Testing: $URL"
          
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$URL")
          
          if [ "$STATUS" == "200" ]; then
            echo "✅ CDN is available!"
          else
            echo "⚠️  CDN returned status: $STATUS (may take a few more minutes)"
          fi
  
  notify-success:
    name: Notify Success
    runs-on: ubuntu-latest
    needs: [security-tests, purge-cdn]
    if: success()
    
    steps:
      - name: Success notification
        run: |
          echo "🎉 FrontendRAFT published successfully!"
          echo "CDN URL: https://cdn.jsdelivr.net/gh/${{ github.repository }}@${{ github.ref_name }}/src/index.js"